# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_hostfxr <- function() {
    .Call(`_IronR_load_hostfxr`)
}

netcore5_init0 <- function() {
    .Call(`_IronR_netcore5_init0`)
}

rcpp_hello_world <- function() {
    .Call(`_IronR_rcpp_hello_world`)
}

